import {
  Asset,
  IoTDevice,
  FaultCodeAnalytics,
  WorkOrder,
  PMScheduleEvent,
  Contract,
  AlertItem,
  ReportItem,
  Engineer,
  SystemStatusIndicator,
} from '@/types';

export const mockAssets: Asset[] = [
  {
    id: 'EQ-204',
    name: 'Centrifugal Chiller A',
    category: 'HVAC & Cooling',
    location: 'Main Hospital Campus',
    floor: 'Basement B2 Plant Room',
    healthScore: 42,
    riskScore: 88,
    riskLevel: 'HIGH',
    iotStatus: 'critical',
    lastFaultDate: '2026-09-28',
    lastFaultCode: 'E-204',
    pmStatus: 'overdue',
    contractStatus: 'AMC',
    contractId: 'CTR-8801',
    installedDate: '2019-04-12',
    manufacturer: 'Carrier Trane Industrial',
    model: 'Apex-9000C',
    serialNumber: 'CT-9000C-44819',
    warrantyExpiry: '2024-04-12',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    trend30d: [78, 75, 70, 68, 62, 58, 52, 49, 44, 42],
    riskContributingFactors: [
      'Discharge temperature exceeded 38°C (critical threshold 35°C)',
      '3 recurring fault events (E-204) in the last 30 days',
      'Preventive Maintenance is 14 days overdue',
      'Contract AMC renewal window approaching in 28 days',
    ],
  },
  {
    id: 'EQ-108',
    name: '3.0T High-Field MRI Scanner',
    category: 'Medical Imaging',
    location: 'Radiology Wing',
    floor: 'Floor 1, Suite 102',
    healthScore: 58,
    riskScore: 82,
    riskLevel: 'HIGH',
    iotStatus: 'warning',
    lastFaultDate: '2026-09-30',
    lastFaultCode: 'T-402',
    pmStatus: 'due',
    contractStatus: 'CMC',
    contractId: 'CTR-9104',
    installedDate: '2021-08-15',
    manufacturer: 'Siemens Healthineers',
    model: 'Magnetom Vida 3T',
    serialNumber: 'SH-MV-81203',
    warrantyExpiry: '2026-08-15',
    coordinates: { lat: 37.7751, lng: -122.4189 },
    trend30d: [85, 82, 80, 74, 71, 68, 65, 62, 60, 58],
    riskContributingFactors: [
      'Cryogenic cold-head vibration frequency shifted by +18%',
      'Helium pressure slight drift detected',
      'Quarterly PM due within 3 days',
    ],
  },
  {
    id: 'EQ-312',
    name: 'Emergency Backup Diesel Generator 1.5MW',
    category: 'Power & Utilities',
    location: 'North Substation Yard',
    floor: 'Ground Exterior',
    healthScore: 68,
    riskScore: 64,
    riskLevel: 'MEDIUM',
    iotStatus: 'warning',
    lastFaultDate: '2026-09-22',
    lastFaultCode: 'P-109',
    pmStatus: 'due',
    contractStatus: 'AMC',
    contractId: 'CTR-7720',
    installedDate: '2020-01-10',
    manufacturer: 'Caterpillar',
    model: 'CAT 3512B',
    serialNumber: 'CAT-3512-9901',
    warrantyExpiry: '2025-01-10',
    trend30d: [76, 75, 75, 73, 71, 70, 69, 68, 68, 68],
    riskContributingFactors: [
      'Coolant pre-heater sensor intermittently dropping signal',
      'Load test scheduled for next week',
    ],
  },
  {
    id: 'EQ-405',
    name: 'Air Handling Unit AHU-04 (Cleanroom)',
    category: 'HVAC & Cooling',
    location: 'Surgery & ICU Block',
    floor: 'Roof Plant Level 4',
    healthScore: 72,
    riskScore: 54,
    riskLevel: 'MEDIUM',
    iotStatus: 'online',
    lastFaultDate: '2026-09-15',
    lastFaultCode: 'V-88',
    pmStatus: 'ok',
    contractStatus: 'AMC',
    contractId: 'CTR-8801',
    installedDate: '2022-03-20',
    manufacturer: 'Daikin Applied',
    model: 'Vision AHU-600',
    serialNumber: 'DK-AHU-3321',
    warrantyExpiry: '2027-03-20',
    trend30d: [80, 80, 78, 77, 75, 74, 73, 72, 72, 72],
    riskContributingFactors: [
      'HEPA filter differential pressure nearing warning band (240 Pa)',
    ],
  },
  {
    id: 'EQ-519',
    name: 'Main Substation 2000kVA Transformer',
    category: 'Power & Utilities',
    location: 'Main Hospital Campus',
    floor: 'Vault Substation A',
    healthScore: 89,
    riskScore: 18,
    riskLevel: 'LOW',
    iotStatus: 'online',
    lastFaultDate: '2026-07-10',
    lastFaultCode: 'T-101',
    pmStatus: 'ok',
    contractStatus: 'CMC',
    contractId: 'CTR-7720',
    installedDate: '2018-11-05',
    manufacturer: 'ABB Power Grids',
    model: 'Resibloc 2000',
    serialNumber: 'ABB-RB-7711',
    warrantyExpiry: '2028-11-05',
    trend30d: [90, 89, 89, 90, 89, 89, 88, 89, 89, 89],
    riskContributingFactors: ['All telemetry nominal; Dissolved gas analysis normal'],
  },
  {
    id: 'EQ-602',
    name: 'Passenger Traction Elevator #3',
    category: 'Vertical Transport',
    location: 'West Patient Tower',
    floor: 'Shaft 3 (Floors B2-12)',
    healthScore: 81,
    riskScore: 26,
    riskLevel: 'LOW',
    iotStatus: 'online',
    lastFaultDate: '2026-08-04',
    lastFaultCode: 'D-201',
    pmStatus: 'ok',
    contractStatus: 'CMC',
    contractId: 'CTR-6612',
    installedDate: '2019-09-18',
    manufacturer: 'Otis Elevator Co',
    model: 'SkyRise High-Speed',
    serialNumber: 'OT-SR-4192',
    warrantyExpiry: '2024-09-18',
    trend30d: [84, 83, 83, 82, 82, 81, 81, 81, 81, 81],
    riskContributingFactors: ['Door cycle wear index at 32% of threshold'],
  },
  {
    id: 'EQ-711',
    name: 'Reverse Osmosis Water Purification System',
    category: 'Water & Steam',
    location: 'Dialysis Center',
    floor: 'Floor 2 Utility Core',
    healthScore: 48,
    riskScore: 86,
    riskLevel: 'HIGH',
    iotStatus: 'critical',
    lastFaultDate: '2026-10-01',
    lastFaultCode: 'F-301',
    pmStatus: 'overdue',
    contractStatus: 'AMC',
    contractId: 'CTR-5510',
    installedDate: '2021-02-14',
    manufacturer: 'Evoqua Water Technologies',
    model: 'Vantage Med-RO',
    serialNumber: 'EV-RO-9021',
    warrantyExpiry: '2025-02-14',
    trend30d: [78, 74, 70, 66, 60, 56, 52, 50, 49, 48],
    riskContributingFactors: [
      'Membrane pressure drop exceeds allowable limit by 24%',
      'Permeate conductivity spike above clinical threshold',
      'Emergency filter sanitize PM overdue by 5 days',
    ],
  },
  {
    id: 'EQ-820',
    name: 'High-Pressure Steam Boiler #2',
    category: 'Water & Steam',
    location: 'Central Energy Plant',
    floor: 'Boiler Hall Level 1',
    healthScore: 64,
    riskScore: 61,
    riskLevel: 'MEDIUM',
    iotStatus: 'warning',
    lastFaultDate: '2026-09-18',
    lastFaultCode: 'B-108',
    pmStatus: 'ok',
    contractStatus: 'AMC',
    contractId: 'CTR-5510',
    installedDate: '2017-06-30',
    manufacturer: 'Cleaver-Brooks',
    model: 'CB-700-600HP',
    serialNumber: 'CB-600-44910',
    warrantyExpiry: '2022-06-30',
    trend30d: [70, 69, 68, 68, 66, 65, 65, 64, 64, 64],
    riskContributingFactors: [
      'Flue gas oxygen sensor drift detected',
      'Blowdown cycle frequency requires recalibration',
    ],
  },
  {
    id: 'EQ-905',
    name: 'Linear Accelerator (LINAC Radiotherapy)',
    category: 'Medical Imaging',
    location: 'Cancer Care Pavilion',
    floor: 'Vault 2 Sub-level',
    healthScore: 92,
    riskScore: 14,
    riskLevel: 'LOW',
    iotStatus: 'online',
    lastFaultDate: '2026-06-12',
    lastFaultCode: 'L-002',
    pmStatus: 'ok',
    contractStatus: 'CMC',
    contractId: 'CTR-9104',
    installedDate: '2023-01-15',
    manufacturer: 'Varian Medical',
    model: 'TrueBeam STx',
    serialNumber: 'VM-TB-55102',
    warrantyExpiry: '2028-01-15',
    trend30d: [94, 94, 93, 93, 92, 92, 92, 92, 92, 92],
    riskContributingFactors: ['Beam calibration and waveguide pressure optimal'],
  },
  {
    id: 'EQ-142',
    name: 'Dual Screw Water Chiller B',
    category: 'HVAC & Cooling',
    location: 'Main Hospital Campus',
    floor: 'Basement B2 Plant Room',
    healthScore: 76,
    riskScore: 38,
    riskLevel: 'LOW',
    iotStatus: 'online',
    lastFaultDate: '2026-08-19',
    lastFaultCode: 'E-104',
    pmStatus: 'ok',
    contractStatus: 'AMC',
    contractId: 'CTR-8801',
    installedDate: '2020-04-12',
    manufacturer: 'Carrier Trane Industrial',
    model: 'Apex-8000S',
    serialNumber: 'CT-8000S-1120',
    warrantyExpiry: '2025-04-12',
    trend30d: [79, 79, 78, 77, 77, 76, 76, 76, 76, 76],
    riskContributingFactors: ['Compressor run hours balanced; oil analysis passed'],
  },
  {
    id: 'EQ-220',
    name: 'Medical Air Compressor Duplex',
    category: 'Medical Gas Systems',
    location: 'Surgery & ICU Block',
    floor: 'Basement Utility Vault',
    healthScore: 84,
    riskScore: 22,
    riskLevel: 'LOW',
    iotStatus: 'online',
    lastFaultDate: '2026-07-29',
    lastFaultCode: 'A-102',
    pmStatus: 'ok',
    contractStatus: 'AMC',
    contractId: 'CTR-4412',
    installedDate: '2021-10-10',
    manufacturer: 'BeaconMedaes',
    model: 'ScrollMed Duplex',
    serialNumber: 'BM-SM-3391',
    warrantyExpiry: '2026-10-10',
    trend30d: [86, 85, 85, 85, 84, 84, 84, 84, 84, 84],
    riskContributingFactors: ['Dew point monitor -42°C (well below -39°C limit)'],
  },
  {
    id: 'EQ-099',
    name: 'Service Freight Elevator #1',
    category: 'Vertical Transport',
    location: 'Supply Logistics Hub',
    floor: 'Loading Dock & Spine',
    healthScore: 52,
    riskScore: 78,
    riskLevel: 'HIGH',
    iotStatus: 'offline',
    lastFaultDate: '2026-09-29',
    lastFaultCode: 'D-304',
    pmStatus: 'overdue',
    contractStatus: 'Expired',
    contractId: 'CTR-6612',
    installedDate: '2016-05-18',
    manufacturer: 'Schindler Elevator',
    model: 'Schindler 2600 Freight',
    serialNumber: 'SC-2600-8819',
    warrantyExpiry: '2021-05-18',
    trend30d: [65, 62, 60, 58, 55, 54, 53, 52, 52, 52],
    riskContributingFactors: [
      'Telemetry gateway lost connectivity 36h ago',
      'Contract expired 12 days ago without active renewal',
      'Hydraulic oil pump temperature sensor erratic',
    ],
  },
];

// Helper to generate realistic historical time series points
function generateTimeSeries(pointsCount: number, base: number, variance: number, trend: number, spikeIndex?: number): { timestamp: string; time: string; value: number }[] {
  const result = [];
  const now = new Date('2026-10-01T14:00:00Z').getTime();
  const stepMs = (24 * 3600 * 1000) / pointsCount;
  for (let i = 0; i < pointsCount; i++) {
    const timeMs = now - (pointsCount - i) * stepMs;
    const d = new Date(timeMs);
    let val = base + Math.sin(i / 3) * variance + (i / pointsCount) * trend;
    if (spikeIndex !== undefined && Math.abs(i - spikeIndex) <= 1) {
      val += variance * 2.8;
    }
    result.push({
      timestamp: d.toISOString(),
      time: d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      value: parseFloat(val.toFixed(1)),
    });
  }
  return result;
}

export const mockIoTDevices: IoTDevice[] = [
  {
    id: 'DEV-CHILLER-TEMP',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    location: 'Basement B2 Plant Room',
    sensorType: 'Temperature',
    currentReading: 38.4,
    unit: '°C',
    status: 'critical',
    minThreshold: 15.0,
    maxThreshold: 30.0,
    warningThreshold: 32.0,
    criticalThreshold: 35.0,
    lastSeen: 'Just now (10s ago)',
    history: {
      '1h': generateTimeSeries(12, 36.5, 1.2, 1.5, 10),
      '6h': generateTimeSeries(24, 33.0, 2.0, 4.0, 20),
      '24h': generateTimeSeries(30, 28.5, 2.5, 9.0, 26),
      '7d': generateTimeSeries(35, 26.0, 3.0, 11.0, 31),
      '30d': generateTimeSeries(30, 24.0, 3.5, 13.0, 28),
    },
    anomalies: [
      {
        id: 'ANOM-881',
        timestamp: '2026-10-01 13:42',
        reading: 38.4,
        threshold: 35.0,
        deviation: '+3.4°C over critical limit',
        durationMinutes: 47,
        acknowledged: false,
        severity: 'critical',
      },
      {
        id: 'ANOM-872',
        timestamp: '2026-09-30 22:15',
        reading: 36.1,
        threshold: 35.0,
        deviation: '+1.1°C over critical limit',
        durationMinutes: 32,
        acknowledged: true,
        acknowledgedBy: 'Marcus Vance (Lead Tech)',
        severity: 'high',
      },
      {
        id: 'ANOM-840',
        timestamp: '2026-09-28 09:10',
        reading: 34.2,
        threshold: 32.0,
        deviation: '+2.2°C warning band',
        durationMinutes: 65,
        acknowledged: true,
        acknowledgedBy: 'Sara Lin (Operations)',
        severity: 'medium',
      },
    ],
  },
  {
    id: 'DEV-CHILLER-VIB',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    location: 'Basement B2 Plant Room',
    sensorType: 'Vibration',
    currentReading: 4.8,
    unit: 'mm/s',
    status: 'warning',
    minThreshold: 0.2,
    maxThreshold: 3.5,
    warningThreshold: 3.8,
    criticalThreshold: 5.5,
    lastSeen: '1 min ago',
    history: {
      '1h': generateTimeSeries(12, 4.5, 0.4, 0.2),
      '6h': generateTimeSeries(24, 4.0, 0.5, 0.7),
      '24h': generateTimeSeries(30, 3.2, 0.6, 1.5, 24),
      '7d': generateTimeSeries(35, 2.8, 0.7, 1.8),
      '30d': generateTimeSeries(30, 2.5, 0.8, 2.0),
    },
    anomalies: [
      {
        id: 'ANOM-880',
        timestamp: '2026-10-01 11:20',
        reading: 4.8,
        threshold: 3.8,
        deviation: '+1.0 mm/s above warning',
        durationMinutes: 120,
        acknowledged: false,
        severity: 'high',
      },
    ],
  },
  {
    id: 'DEV-RO-PRESSURE',
    assetId: 'EQ-711',
    assetName: 'Reverse Osmosis Water Purification System',
    location: 'Dialysis Center, Floor 2',
    sensorType: 'Pressure',
    currentReading: 14.8,
    unit: 'bar',
    status: 'critical',
    minThreshold: 6.0,
    maxThreshold: 11.5,
    warningThreshold: 12.0,
    criticalThreshold: 14.0,
    lastSeen: 'Just now',
    history: {
      '1h': generateTimeSeries(12, 14.2, 0.5, 0.6, 11),
      '6h': generateTimeSeries(24, 13.0, 0.8, 1.8, 22),
      '24h': generateTimeSeries(30, 11.2, 1.0, 3.5, 27),
      '7d': generateTimeSeries(35, 10.0, 1.2, 4.6),
      '30d': generateTimeSeries(30, 9.5, 1.3, 5.0),
    },
    anomalies: [
      {
        id: 'ANOM-879',
        timestamp: '2026-10-01 12:05',
        reading: 14.8,
        threshold: 14.0,
        deviation: '+0.8 bar pressure head overflow',
        durationMinutes: 85,
        acknowledged: false,
        severity: 'critical',
      },
    ],
  },
  {
    id: 'DEV-MRI-CRYOVIB',
    assetId: 'EQ-108',
    assetName: '3.0T High-Field MRI Scanner',
    location: 'Radiology Wing Suite 102',
    sensorType: 'Vibration',
    currentReading: 3.9,
    unit: 'mm/s',
    status: 'warning',
    minThreshold: 0.1,
    maxThreshold: 3.0,
    warningThreshold: 3.2,
    criticalThreshold: 4.5,
    lastSeen: '30s ago',
    history: {
      '1h': generateTimeSeries(12, 3.8, 0.2, 0.1),
      '6h': generateTimeSeries(24, 3.5, 0.3, 0.3),
      '24h': generateTimeSeries(30, 2.9, 0.4, 0.9),
      '7d': generateTimeSeries(35, 2.4, 0.5, 1.4),
      '30d': generateTimeSeries(30, 2.2, 0.5, 1.6),
    },
    anomalies: [
      {
        id: 'ANOM-860',
        timestamp: '2026-09-30 18:40',
        reading: 3.9,
        threshold: 3.2,
        deviation: '+0.7 mm/s harmonic drift',
        durationMinutes: 240,
        acknowledged: true,
        acknowledgedBy: 'Dr. Elena Rostova',
        severity: 'medium',
      },
    ],
  },
  {
    id: 'DEV-GEN-CURRENT',
    assetId: 'EQ-312',
    assetName: 'Emergency Backup Diesel Generator 1.5MW',
    location: 'North Substation Yard',
    sensorType: 'Current',
    currentReading: 410,
    unit: 'A',
    status: 'online',
    minThreshold: 50,
    maxThreshold: 1800,
    warningThreshold: 1600,
    criticalThreshold: 1900,
    lastSeen: '2 min ago',
    history: {
      '1h': generateTimeSeries(12, 400, 20, 10),
      '6h': generateTimeSeries(24, 390, 30, 20),
      '24h': generateTimeSeries(30, 380, 40, 25),
      '7d': generateTimeSeries(35, 370, 50, 30),
      '30d': generateTimeSeries(30, 360, 60, 40),
    },
    anomalies: [],
  },
  {
    id: 'DEV-AHU4-DIFFPRESS',
    assetId: 'EQ-405',
    assetName: 'Air Handling Unit AHU-04 (Cleanroom)',
    location: 'Surgery & ICU Block Roof',
    sensorType: 'Pressure',
    currentReading: 238,
    unit: 'Pa',
    status: 'online',
    minThreshold: 50,
    maxThreshold: 250,
    warningThreshold: 240,
    criticalThreshold: 280,
    lastSeen: '1 min ago',
    history: {
      '1h': generateTimeSeries(12, 235, 5, 2),
      '6h': generateTimeSeries(24, 230, 8, 7),
      '24h': generateTimeSeries(30, 220, 10, 16),
      '7d': generateTimeSeries(35, 205, 12, 28),
      '30d': generateTimeSeries(30, 190, 15, 45),
    },
    anomalies: [],
  },
  {
    id: 'DEV-BOILER-TEMP',
    assetId: 'EQ-820',
    assetName: 'High-Pressure Steam Boiler #2',
    location: 'Central Energy Plant',
    sensorType: 'Temperature',
    currentReading: 188.5,
    unit: '°C',
    status: 'warning',
    minThreshold: 120.0,
    maxThreshold: 185.0,
    warningThreshold: 185.0,
    criticalThreshold: 210.0,
    lastSeen: '4 min ago',
    history: {
      '1h': generateTimeSeries(12, 186.0, 2.0, 2.0),
      '6h': generateTimeSeries(24, 182.0, 3.0, 5.0),
      '24h': generateTimeSeries(30, 178.0, 4.0, 9.0),
      '7d': generateTimeSeries(35, 172.0, 5.0, 14.0),
      '30d': generateTimeSeries(30, 168.0, 6.0, 18.0),
    },
    anomalies: [
      {
        id: 'ANOM-851',
        timestamp: '2026-09-30 08:30',
        reading: 188.5,
        threshold: 185.0,
        deviation: '+3.5°C over warning point',
        durationMinutes: 180,
        acknowledged: false,
        severity: 'medium',
      },
    ],
  },
  {
    id: 'DEV-ELEV-OFFLINE',
    assetId: 'EQ-099',
    assetName: 'Service Freight Elevator #1',
    location: 'Supply Logistics Hub',
    sensorType: 'Temperature',
    currentReading: 0,
    unit: '°C',
    status: 'offline',
    minThreshold: 10.0,
    maxThreshold: 65.0,
    warningThreshold: 55.0,
    criticalThreshold: 70.0,
    lastSeen: '36 hours ago (Packet timeout)',
    history: {
      '1h': [],
      '6h': [],
      '24h': [],
      '7d': generateTimeSeries(20, 42.0, 4.0, 0),
      '30d': generateTimeSeries(30, 40.0, 5.0, 2),
    },
    anomalies: [
      {
        id: 'ANOM-811',
        timestamp: '2026-09-30 02:00',
        reading: 0,
        threshold: 10.0,
        deviation: 'Gateway heartbeat loss',
        durationMinutes: 2160,
        acknowledged: false,
        severity: 'high',
      },
    ],
  },
];

export const mockFaults: FaultCodeAnalytics[] = [
  {
    id: 'FC-1',
    code: 'E-204',
    description: 'Compressor High Head Pressure / Thermal Discharge Overheat',
    occurrences: 14,
    affectedAssetsCount: 3,
    affectedAssets: ['EQ-204', 'EQ-142', 'EQ-820'],
    avgResolutionTimeHours: 4.8,
    firstSeen: '2026-06-12',
    lastSeen: '2026-09-28',
    severity: 'critical',
    trend: 'up',
    coOccurringWith: [
      { code: 'V-88', percent: 71 },
      { code: 'T-402', percent: 43 },
    ],
    instances: [
      {
        id: 'FI-901',
        date: '2026-09-28 14:10',
        assetId: 'EQ-204',
        assetName: 'Centrifugal Chiller A',
        location: 'Basement B2 Plant Room',
        severity: 'critical',
        resolutionTimeHours: 5.2,
        resolutionSummary: 'Condenser coils power washed; heat exchanger thermal transfer restored.',
        engineer: 'Marcus Vance',
      },
      {
        id: 'FI-854',
        date: '2026-09-14 09:25',
        assetId: 'EQ-204',
        assetName: 'Centrifugal Chiller A',
        location: 'Basement B2 Plant Room',
        severity: 'high',
        resolutionTimeHours: 4.1,
        resolutionSummary: 'Expansion valve servo adjusted; refrigerant flow corrected.',
        engineer: 'Marcus Vance',
      },
      {
        id: 'FI-799',
        date: '2026-08-30 16:45',
        assetId: 'EQ-204',
        assetName: 'Centrifugal Chiller A',
        location: 'Basement B2 Plant Room',
        severity: 'critical',
        resolutionTimeHours: 5.5,
        resolutionSummary: 'Cooling tower water loop chemical dosing balance recalibrated.',
        engineer: 'Sara Lin',
      },
      {
        id: 'FI-720',
        date: '2026-08-11 11:30',
        assetId: 'EQ-142',
        assetName: 'Dual Screw Water Chiller B',
        location: 'Basement B2 Plant Room',
        severity: 'high',
        resolutionTimeHours: 3.8,
        resolutionSummary: 'Temperature sensor harness re-seated and verified with multimeter.',
        engineer: 'Tariq Al-Mansoor',
      },
    ],
  },
  {
    id: 'FC-2',
    code: 'F-301',
    description: 'Permeate Membrane Differential Pressure Saturation',
    occurrences: 9,
    affectedAssetsCount: 2,
    affectedAssets: ['EQ-711', 'EQ-820'],
    avgResolutionTimeHours: 6.2,
    firstSeen: '2026-07-04',
    lastSeen: '2026-10-01',
    severity: 'critical',
    trend: 'up',
    coOccurringWith: [
      { code: 'P-109', percent: 65 },
    ],
    instances: [
      {
        id: 'FI-920',
        date: '2026-10-01 10:15',
        assetId: 'EQ-711',
        assetName: 'Reverse Osmosis Water Purification System',
        location: 'Dialysis Center Floor 2',
        severity: 'critical',
        resolutionTimeHours: 6.0,
        resolutionSummary: 'Acid/caustic membrane CIP clean performed; flux rate measured.',
        engineer: 'Elena Gomez',
      },
    ],
  },
  {
    id: 'FC-3',
    code: 'V-88',
    description: 'Excessive Rotational Harmonic Vibration / Imbalance',
    occurrences: 8,
    affectedAssetsCount: 4,
    affectedAssets: ['EQ-204', 'EQ-405', 'EQ-312', 'EQ-108'],
    avgResolutionTimeHours: 3.5,
    firstSeen: '2026-05-18',
    lastSeen: '2026-09-15',
    severity: 'high',
    trend: 'stable',
    coOccurringWith: [
      { code: 'E-204', percent: 71 },
    ],
    instances: [
      {
        id: 'FI-882',
        date: '2026-09-15 13:00',
        assetId: 'EQ-405',
        assetName: 'Air Handling Unit AHU-04 (Cleanroom)',
        location: 'Roof Plant Level 4',
        severity: 'medium',
        resolutionTimeHours: 2.8,
        resolutionSummary: 'Blower fan belts tensioned and dynamically laser balanced.',
        engineer: 'Tariq Al-Mansoor',
      },
    ],
  },
  {
    id: 'FC-4',
    code: 'T-402',
    description: 'Cryogenic Shield Temperature Drift Anomaly',
    occurrences: 5,
    affectedAssetsCount: 1,
    affectedAssets: ['EQ-108'],
    avgResolutionTimeHours: 7.4,
    firstSeen: '2026-08-01',
    lastSeen: '2026-09-30',
    severity: 'high',
    trend: 'up',
    coOccurringWith: [
      { code: 'E-204', percent: 43 },
    ],
    instances: [
      {
        id: 'FI-915',
        date: '2026-09-30 08:00',
        assetId: 'EQ-108',
        assetName: '3.0T High-Field MRI Scanner',
        location: 'Radiology Wing',
        severity: 'high',
        resolutionTimeHours: 7.2,
        resolutionSummary: 'Adsorber replacement and helium compressor recharge initiated.',
        engineer: 'Siemens Certified Rep',
      },
    ],
  },
  {
    id: 'FC-5',
    code: 'P-109',
    description: 'Fuel Injection Pressure Variation Outside Calibration Band',
    occurrences: 4,
    affectedAssetsCount: 2,
    affectedAssets: ['EQ-312', 'EQ-820'],
    avgResolutionTimeHours: 4.0,
    firstSeen: '2026-07-22',
    lastSeen: '2026-09-22',
    severity: 'medium',
    trend: 'down',
    coOccurringWith: [
      { code: 'F-301', percent: 65 },
    ],
    instances: [
      {
        id: 'FI-861',
        date: '2026-09-22 15:30',
        assetId: 'EQ-312',
        assetName: 'Emergency Backup Diesel Generator 1.5MW',
        location: 'North Substation Yard',
        severity: 'medium',
        resolutionTimeHours: 3.5,
        resolutionSummary: 'Fuel filter element replaced and priming pump purged.',
        engineer: 'Sara Lin',
      },
    ],
  },
];

export const mockMTBFData = [
  { category: 'Medical Imaging', mtbfDays: 142, benchmarkDays: 180, drivers: 'EQ-108 cold-head vibration' },
  { category: 'HVAC & Cooling', mtbfDays: 48, benchmarkDays: 90, drivers: 'EQ-204 thermal overheat recurrence' },
  { category: 'Power & Utilities', mtbfDays: 210, benchmarkDays: 180, drivers: 'Transformer EQ-519 highly stable' },
  { category: 'Water & Steam', mtbfDays: 52, benchmarkDays: 120, drivers: 'EQ-711 RO membrane scaling' },
  { category: 'Vertical Transport', mtbfDays: 115, benchmarkDays: 150, drivers: 'EQ-099 freight elevator door cycle' },
  { category: 'Medical Gas Systems', mtbfDays: 290, benchmarkDays: 240, drivers: 'EQ-220 optimal duplex operation' },
];

export const mockEngineers: Engineer[] = [
  {
    id: 'ENG-1',
    name: 'Marcus Vance',
    initials: 'MV',
    role: 'Senior HVAC & Thermal Specialist',
    activeWorkOrders: 3,
    nextAvailable: 'Today 16:30',
    avatarColor: '#4F46E5',
  },
  {
    id: 'ENG-2',
    name: 'Sara Lin',
    initials: 'SL',
    role: 'Electrical & Automation Systems',
    activeWorkOrders: 2,
    nextAvailable: 'Tomorrow 09:00',
    avatarColor: '#059669',
  },
  {
    id: 'ENG-3',
    name: 'Tariq Al-Mansoor',
    initials: 'TA',
    role: 'Vibration & Mechanical Diagnostics',
    activeWorkOrders: 1,
    nextAvailable: 'Today 15:00',
    avatarColor: '#D97706',
  },
  {
    id: 'ENG-4',
    name: 'Dr. Elena Gomez',
    initials: 'EG',
    role: 'Clinical Equipment & Biomedical Engineer',
    activeWorkOrders: 4,
    nextAvailable: 'Tomorrow 13:00',
    avatarColor: '#DC2626',
  },
];

export const mockPMSchedules: PMScheduleEvent[] = [
  {
    id: 'PM-2026-1001',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    type: 'Monthly Thermal Condenser Overhaul',
    engineer: 'Marcus Vance',
    engineerInitials: 'MV',
    date: '2026-09-17',
    status: 'overdue',
    contractRequired: true,
    notes: 'Mandated by AMC clause 4.2. Overdue by 14 days.',
  },
  {
    id: 'PM-2026-1002',
    assetId: 'EQ-711',
    assetName: 'Reverse Osmosis Water Purification System',
    type: 'Sanitization & Membrane Replacement',
    engineer: 'Elena Gomez',
    engineerInitials: 'EG',
    date: '2026-09-26',
    status: 'overdue',
    contractRequired: true,
    notes: 'Clinical water purity compliance requirement.',
  },
  {
    id: 'PM-2026-1003',
    assetId: 'EQ-108',
    assetName: '3.0T High-Field MRI Scanner',
    type: 'Cryogenic Coldhead & RF Coil Tune',
    engineer: 'Elena Gomez',
    engineerInitials: 'EG',
    date: '2026-10-04',
    status: 'upcoming',
    contractRequired: true,
    notes: 'Siemens warranty validation inspection.',
  },
  {
    id: 'PM-2026-1004',
    assetId: 'EQ-312',
    assetName: 'Emergency Backup Diesel Generator 1.5MW',
    type: 'Load Bank 100% Capacity Test',
    engineer: 'Sara Lin',
    engineerInitials: 'SL',
    date: '2026-10-01',
    status: 'due_today',
    contractRequired: true,
    notes: 'Quarterly compliance run.',
  },
  {
    id: 'PM-2026-1005',
    assetId: 'EQ-405',
    assetName: 'Air Handling Unit AHU-04 (Cleanroom)',
    type: 'HEPA Filter Differential Pressure Check',
    engineer: 'Tariq Al-Mansoor',
    engineerInitials: 'TA',
    date: '2026-10-08',
    status: 'upcoming',
    contractRequired: false,
    notes: 'Internal hospital operations cadence.',
  },
  {
    id: 'PM-2026-1006',
    assetId: 'EQ-519',
    assetName: 'Main Substation 2000kVA Transformer',
    type: 'Dielectric Oil Breakdown & Infrared Scan',
    engineer: 'Sara Lin',
    engineerInitials: 'SL',
    date: '2026-09-12',
    status: 'completed',
    contractRequired: true,
    notes: 'Passed all tests with high margin. Report signed.',
  },
  {
    id: 'PM-2026-1007',
    assetId: 'EQ-602',
    assetName: 'Passenger Traction Elevator #3',
    type: 'Governor & Brake Shoe Clearance Audit',
    engineer: 'Tariq Al-Mansoor',
    engineerInitials: 'TA',
    date: '2026-09-18',
    status: 'completed',
    contractRequired: true,
    notes: 'State elevator safety certification renewed.',
  },
  {
    id: 'PM-2026-1008',
    assetId: 'EQ-220',
    assetName: 'Medical Air Compressor Duplex',
    type: 'Desiccant Dryer Cartridge Swap',
    engineer: 'Marcus Vance',
    engineerInitials: 'MV',
    date: '2026-09-24',
    status: 'completed',
    contractRequired: true,
    notes: 'Dew point returned to optimal level.',
  },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-8891',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    type: 'Emergency',
    priority: 'critical',
    assignedEngineer: 'Marcus Vance',
    createdAt: '2026-10-01 09:30',
    dueDate: '2026-10-01 18:00',
    status: 'In Progress',
    description: 'Diagnose and resolve high discharge temperature (38.4°C) causing risk of thermal safety trip.',
  },
  {
    id: 'WO-8890',
    assetId: 'EQ-711',
    assetName: 'Reverse Osmosis Water Purification System',
    type: 'Corrective',
    priority: 'critical',
    assignedEngineer: 'Elena Gomez',
    createdAt: '2026-10-01 08:00',
    dueDate: '2026-10-02 12:00',
    status: 'Open',
    description: 'Immediate membrane CIP chemical wash and differential pressure transmitter recalibration.',
  },
  {
    id: 'WO-8842',
    assetId: 'EQ-108',
    assetName: '3.0T High-Field MRI Scanner',
    type: 'Preventive',
    priority: 'high',
    assignedEngineer: 'Elena Gomez',
    createdAt: '2026-09-29 11:00',
    dueDate: '2026-10-04 17:00',
    status: 'Open',
    description: 'Cryogenic cold-head vibration inspection and helium line pressure leak check.',
  },
  {
    id: 'WO-8812',
    assetId: 'EQ-312',
    assetName: 'Emergency Backup Diesel Generator 1.5MW',
    type: 'Inspection',
    priority: 'medium',
    assignedEngineer: 'Sara Lin',
    createdAt: '2026-09-28 14:00',
    dueDate: '2026-10-01 16:00',
    status: 'In Progress',
    description: 'Quarterly load bank testing and automated transfer switch (ATS) synchronism verification.',
  },
  {
    id: 'WO-8770',
    assetId: 'EQ-405',
    assetName: 'Air Handling Unit AHU-04 (Cleanroom)',
    type: 'Preventive',
    priority: 'medium',
    assignedEngineer: 'Tariq Al-Mansoor',
    createdAt: '2026-09-25 10:00',
    dueDate: '2026-10-08 17:00',
    status: 'Open',
    description: 'Inspect HEPA filter seal integrity and replace pre-filters.',
  },
  {
    id: 'WO-8651',
    assetId: 'EQ-519',
    assetName: 'Main Substation 2000kVA Transformer',
    type: 'Preventive',
    priority: 'low',
    assignedEngineer: 'Sara Lin',
    createdAt: '2026-09-10 09:00',
    dueDate: '2026-09-12 18:00',
    completedAt: '2026-09-12 16:45',
    status: 'Completed',
    description: 'Dielectric breakdown testing of transformer oil and infrared thermography scan.',
  },
  {
    id: 'WO-8610',
    assetId: 'EQ-602',
    assetName: 'Passenger Traction Elevator #3',
    type: 'Preventive',
    priority: 'low',
    assignedEngineer: 'Tariq Al-Mansoor',
    createdAt: '2026-09-15 08:30',
    dueDate: '2026-09-18 17:00',
    completedAt: '2026-09-18 15:30',
    status: 'Completed',
    description: 'Inspect car guide shoes, wire rope tension, and car leveling accuracy.',
  },
  {
    id: 'WO-8550',
    assetId: 'EQ-099',
    assetName: 'Service Freight Elevator #1',
    type: 'Corrective',
    priority: 'high',
    assignedEngineer: 'Tariq Al-Mansoor',
    createdAt: '2026-09-29 16:00',
    dueDate: '2026-09-30 18:00',
    status: 'Cancelled',
    description: 'Cancelled due to vendor contract lapse; work order pending AMC renewal authorization.',
  },
];

export const mockContracts: Contract[] = [
  {
    id: 'CTR-8801',
    name: 'HVAC Comprehensive Plant Maintenance Contract',
    vendor: 'Carrier Commercial Service Corp',
    type: 'AMC',
    coveredAssets: ['EQ-204', 'EQ-142', 'EQ-405'],
    startDate: '2025-10-29',
    endDate: '2026-10-29',
    value: 145000,
    complianceScore: 78,
    pmCadence: 'Monthly (12x / yr)',
    status: 'renewal_initiated',
    daysToExpiry: 28,
    renewalRisk: 'HIGH',
    renewalRiskReason: 'Expires in 28 days with 1 overdue PM on high-risk Chiller EQ-204 and vendor price renegotiation active.',
    scope: '24/7 emergency response within 2 hours, monthly preventive maintenance, all compressor and pump parts included up to $15k per event.',
    documents: [
      { id: 'DOC-1', name: 'Master_Service_Agreement_Carrier_2025.pdf', type: 'PDF', uploadDate: '2025-10-28', size: '2.4 MB', url: '#' },
      { id: 'DOC-2', name: 'SLA_Response_Time_Annex_B.pdf', type: 'PDF', uploadDate: '2025-10-28', size: '840 KB', url: '#' },
      { id: 'DOC-3', name: 'Q3_PM_Completion_Signoff_Report.pdf', type: 'PDF', uploadDate: '2026-07-02', size: '1.2 MB', url: '#' },
    ],
    activityLog: [
      { date: '2026-09-29', action: 'Renewal negotiation package sent to Carrier procurement team', user: 'Facilities Director' },
      { date: '2026-09-18', action: 'Overdue PM notification flagged by Compliance Engine', user: 'System Automated' },
      { date: '2026-07-02', action: 'Q2 Performance review approved with 94% uptime SLA met', user: 'Operations Manager' },
    ],
  },
  {
    id: 'CTR-9104',
    name: 'Advanced Diagnostic Imaging Comprehensive CMC',
    vendor: 'Siemens Healthineers Solutions',
    type: 'CMC',
    coveredAssets: ['EQ-108', 'EQ-905'],
    startDate: '2024-08-15',
    endDate: '2027-08-15',
    value: 480000,
    complianceScore: 96,
    pmCadence: 'Quarterly + 24/7 Tele-support',
    status: 'active',
    daysToExpiry: 318,
    renewalRisk: 'LOW',
    renewalRiskReason: 'Multi-year active contract with 96% compliance rate and guaranteed tube/magnet replacement coverage.',
    scope: 'Full comprehensive coverage including cold-head, magnet helium quench insurance, detector calibration, and certified clinical application training.',
    documents: [
      { id: 'DOC-4', name: 'Siemens_3T_LINAC_CMC_Executed.pdf', type: 'PDF', uploadDate: '2024-08-14', size: '5.1 MB', url: '#' },
      { id: 'DOC-5', name: 'Helium_Boiloff_Coverage_Endorsement.pdf', type: 'PDF', uploadDate: '2024-08-14', size: '420 KB', url: '#' },
    ],
    activityLog: [
      { date: '2026-08-10', action: 'Annual helium replenishment documented and verified', user: 'Dr. Elena Gomez' },
      { date: '2026-06-15', action: 'Firmware security patch 4.2 applied to TrueBeam LINAC', user: 'Siemens Certified Rep' },
    ],
  },
  {
    id: 'CTR-7720',
    name: 'Substation & Emergency Power Generation AMC',
    vendor: 'Schneider Electric Services',
    type: 'AMC',
    coveredAssets: ['EQ-312', 'EQ-519'],
    startDate: '2025-01-10',
    endDate: '2027-01-10',
    value: 92000,
    complianceScore: 92,
    pmCadence: 'Bi-monthly & Semi-annual load bank',
    status: 'active',
    daysToExpiry: 101,
    renewalRisk: 'LOW',
    renewalRiskReason: 'Healthy compliance and timely PM completion. Renewal discussions slated for Q4.',
    scope: 'Medium voltage switchgear, transformer oil dissolved gas testing, generator oil & coolant analysis, ATS testing.',
    documents: [
      { id: 'DOC-6', name: 'Schneider_Power_AMC_Executed.pdf', type: 'PDF', uploadDate: '2025-01-08', size: '3.1 MB', url: '#' },
    ],
    activityLog: [
      { date: '2026-09-12', action: 'Transformer 2000kVA annual certification uploaded', user: 'Sara Lin' },
    ],
  },
  {
    id: 'CTR-5510',
    name: 'Critical Water Purification & Steam Plant Support',
    vendor: 'Veolia Water Technologies',
    type: 'AMC',
    coveredAssets: ['EQ-711', 'EQ-820'],
    startDate: '2025-10-14',
    endDate: '2026-10-14',
    value: 68000,
    complianceScore: 68,
    pmCadence: 'Monthly',
    status: 'under_review',
    daysToExpiry: 13,
    renewalRisk: 'HIGH',
    renewalRiskReason: 'Expires in 13 days! Multiple unresolved pressure alarms on EQ-711 and vendor SLA penalty review underway.',
    scope: 'RO membrane replacements, chemical cleaning agents, steam boiler burner tuning, water hardness testing.',
    documents: [
      { id: 'DOC-7', name: 'Veolia_Water_Steam_Service_Contract.pdf', type: 'PDF', uploadDate: '2025-10-10', size: '1.9 MB', url: '#' },
      { id: 'DOC-8', name: 'Dialysis_Water_Quality_Standards_Annex.pdf', type: 'PDF', uploadDate: '2025-10-10', size: '920 KB', url: '#' },
    ],
    activityLog: [
      { date: '2026-09-30', action: 'Dispute filed regarding overdue RO sanitize maintenance visit', user: 'Operations Manager' },
      { date: '2026-09-20', action: 'Contract renewal notification issued by Veolia account executive', user: 'Vendor Rep' },
    ],
  },
  {
    id: 'CTR-6612',
    name: 'Elevator & Vertical Transportation Fleet CMC',
    vendor: 'Otis Elevator Global Operations',
    type: 'CMC',
    coveredAssets: ['EQ-602', 'EQ-099'],
    startDate: '2023-09-15',
    endDate: '2026-09-19',
    value: 110000,
    complianceScore: 61,
    pmCadence: 'Monthly mandatory code check',
    status: 'lapsed',
    daysToExpiry: -12,
    renewalRisk: 'HIGH',
    renewalRiskReason: 'Contract lapsed 12 days ago. Service freight elevator EQ-099 currently operating without active warranty.',
    scope: 'Full comprehensive maintenance, 24/7 passenger entrapment release within 25 minutes, all motor drive replacements.',
    documents: [
      { id: 'DOC-9', name: 'Otis_Vertical_Transport_CMC_Signed.pdf', type: 'PDF', uploadDate: '2023-09-12', size: '3.6 MB', url: '#' },
    ],
    activityLog: [
      { date: '2026-09-20', action: 'Contract expired without formal renewal signed. Emergency extension requested.', user: 'Facilities Director' },
    ],
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: 'ALT-101',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    severity: 'critical',
    title: 'High Thermal Discharge Exceeds 38°C Safety Margin',
    readingSummary: 'Temp: 38.4°C (Threshold: 32°C critical 35°C)',
    durationMinutes: 47,
    reason: 'Cooling loop thermal anomaly detected co-occurring with compressor head pressure spike.',
    recommendation: 'Immediate physical inspection of condenser water flow rate and power wash cooling coils.',
    ctaLabel: 'Inspect Now',
    ctaAction: 'inspect',
    status: 'active',
    timestamp: '2026-10-01 13:42',
    category: 'iot',
    riskLevel: 'CRITICAL',
  },
  {
    id: 'ALT-102',
    assetId: 'EQ-711',
    assetName: 'Reverse Osmosis Water Purification System',
    severity: 'critical',
    title: 'Differential Pressure Saturation on Dialysis RO Unit',
    readingSummary: 'Pressure: 14.8 bar (Threshold: 11.5 bar max)',
    durationMinutes: 85,
    reason: 'Membrane fouling suspected; clinical water output rate declining 22%.',
    recommendation: 'Initiate chemical sanitization CIP wash and dispatch biomedical technician.',
    ctaLabel: 'Assign Work Order',
    ctaAction: 'assign',
    status: 'active',
    timestamp: '2026-10-01 12:05',
    category: 'fault',
    riskLevel: 'CRITICAL',
  },
  {
    id: 'ALT-103',
    assetId: 'EQ-204',
    assetName: 'Centrifugal Chiller A',
    severity: 'high',
    title: 'Preventive Maintenance 14 Days Overdue',
    readingSummary: 'Due: 2026-09-17 (14 days past deadline)',
    durationMinutes: 20160,
    reason: 'Mandatory AMC scheduled overhaul missed due to technician scheduling conflict.',
    recommendation: 'Schedule emergency PM maintenance slot to preserve AMC warranty validation.',
    ctaLabel: 'Schedule PM',
    ctaAction: 'schedule_pm',
    status: 'active',
    timestamp: '2026-09-18 09:00',
    category: 'pm',
    riskLevel: 'HIGH',
  },
  {
    id: 'ALT-104',
    assetId: 'EQ-108',
    assetName: '3.0T High-Field MRI Scanner',
    severity: 'high',
    title: 'Cryogenic Coldhead Vibration Harmonic Shift',
    readingSummary: 'Vib: 3.9 mm/s (Threshold: 3.2 mm/s warning)',
    durationMinutes: 240,
    reason: 'Harmonic frequency shift observed on coldhead motor assembly.',
    recommendation: 'Verify helium compressor adsorber hours and check pressure lines.',
    ctaLabel: 'Acknowledge',
    ctaAction: 'acknowledge',
    status: 'active',
    timestamp: '2026-09-30 18:40',
    category: 'iot',
    riskLevel: 'HIGH',
  },
  {
    id: 'ALT-105',
    assetId: 'CTR-5510',
    assetName: 'Veolia Critical Water & Steam Contract',
    severity: 'high',
    title: 'AMC Contract Expiring Within 13 Days',
    readingSummary: 'Expires: 2026-10-14 (Value: $68,000/yr)',
    durationMinutes: 5760,
    reason: 'Contract renewal under review with active vendor performance SLA dispute.',
    recommendation: 'Conduct emergency renewal sign-off to prevent lapse on clinical water systems.',
    ctaLabel: 'Renew Contract',
    ctaAction: 'renew_contract',
    status: 'active',
    timestamp: '2026-09-30 10:00',
    category: 'contract',
    riskLevel: 'HIGH',
  },
  {
    id: 'ALT-106',
    assetId: 'EQ-820',
    assetName: 'High-Pressure Steam Boiler #2',
    severity: 'medium',
    title: 'Boiler Flue Gas Temperature Warning',
    readingSummary: 'Temp: 188.5°C (Threshold: 185°C)',
    durationMinutes: 180,
    reason: 'Air-to-fuel ratio slight drift causing elevated exhaust temperature.',
    recommendation: 'Calibrate burner linkage during next scheduled cycle check.',
    ctaLabel: 'Acknowledge',
    ctaAction: 'acknowledge',
    status: 'active',
    timestamp: '2026-09-30 08:30',
    category: 'iot',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'ALT-107',
    assetId: 'EQ-099',
    assetName: 'Service Freight Elevator #1',
    severity: 'medium',
    title: 'IoT Telemetry Gateway Communication Loss',
    readingSummary: 'Offline for 36 hours',
    durationMinutes: 2160,
    reason: 'Gateway packet timeout; sensor power or switch port disconnected.',
    recommendation: 'Cycle PoE port on network switch N-FloorB2-SW3.',
    ctaLabel: 'Inspect Now',
    ctaAction: 'inspect',
    status: 'active',
    timestamp: '2026-09-30 02:00',
    category: 'iot',
    riskLevel: 'MEDIUM',
  },
  {
    id: 'ALT-108',
    assetId: 'EQ-312',
    assetName: 'Emergency Backup Diesel Generator 1.5MW',
    severity: 'low',
    title: 'Coolant Level Sensor Self-Check Transient Drift',
    readingSummary: 'Reading normalized after 4 minutes',
    durationMinutes: 4,
    reason: 'Minor float switch resistance variation during engine room ambient warming.',
    recommendation: 'Log for routine semi-annual sensor terminal tightening.',
    ctaLabel: 'Acknowledge',
    ctaAction: 'acknowledge',
    status: 'acknowledged',
    timestamp: '2026-09-27 15:12',
    category: 'iot',
    riskLevel: 'LOW',
  },
];

export const mockReports: ReportItem[] = [
  {
    id: 'REP-2026-Q3-01',
    title: 'Hospital Estate Enterprise Risk & Health Assessment',
    type: 'Executive Asset Risk',
    period: 'Q3 2026 (July - September)',
    generatedDate: '2026-10-01 06:00',
    status: 'Ready',
    author: 'AURUM AI Analytics Engine',
    fileSize: '4.8 MB',
    summary: 'Comprehensive audit covering 12 mission-critical asset groups. 3 high-risk assets identified with correlated thermal and vibration precursors. Overall estate health index: 76.4/100.',
    metrics: [
      { label: 'Total Assets Audited', value: 12 },
      { label: 'High-Risk Asset Count', value: 3 },
      { label: 'Mean Time Between Failures', value: '118 days' },
      { label: 'Portfolio Health Index', value: '76.4 / 100' },
    ],
  },
  {
    id: 'REP-2026-M09-02',
    title: 'Monthly AMC/CMC Contract Compliance & SLA Audit',
    type: 'Contract Compliance Audit',
    period: 'September 2026',
    generatedDate: '2026-09-30 23:59',
    status: 'Ready',
    author: 'Compliance Officer (Karen Miller)',
    fileSize: '3.2 MB',
    summary: 'Verification of contractual PM delivery across 5 active vendors. Carrier AMC compliance dropped to 78% due to overdue chiller service. Otis elevator contract expired 12 days ago.',
    metrics: [
      { label: 'Active Contracts', value: 5 },
      { label: 'Contract PM Compliance', value: '84.2%' },
      { label: 'Expiring in 30 Days', value: 2 },
      { label: 'Audit Readiness Score', value: '92%' },
    ],
  },
  {
    id: 'REP-2026-IOT-03',
    title: 'IoT Telemetry Anomaly & Threshold Violation Deep Dive',
    type: 'IoT Anomaly Summary',
    period: 'Last 30 Days',
    generatedDate: '2026-09-29 18:00',
    status: 'Ready',
    author: 'AURUM Edge Gateway Monitor',
    fileSize: '2.1 MB',
    summary: 'Analyzed 432,000 sensor telemetry readings. Detected 18 anomalous excursions across chiller thermal, RO differential pressure, and MRI cold-head vibration channels.',
    metrics: [
      { label: 'Sensor Heartbeat Uptime', value: '99.4%' },
      { label: 'Active Anomalies Captured', value: 4 },
      { label: 'False Positive Suppression', value: '94.2%' },
    ],
  },
  {
    id: 'REP-2026-PM-04',
    title: 'Preventive Maintenance Execution & Work Order Velocity',
    type: 'Maintenance Monthly Review',
    period: 'September 2026',
    generatedDate: '2026-09-28 12:00',
    status: 'Ready',
    author: 'Operations Manager (David Ross)',
    fileSize: '1.9 MB',
    summary: '32 planned PM work orders scheduled; 26 completed on time, 4 overdue, 2 pending parts procurement. Average repair MTTR improved to 4.2 hours.',
    metrics: [
      { label: 'PM Completion Rate', value: '81.2%' },
      { label: 'Average Work Order MTTR', value: '4.2 hrs' },
      { label: 'First-Time Fix Rate', value: '88.5%' },
    ],
  },
];

export const mockSystemStatus: SystemStatusIndicator[] = [
  {
    name: 'IoT Telemetry Gateway',
    status: 'Operational',
    lastUpdated: '12s ago',
    details: 'MQTT brokers and OPC-UA connectors streaming at 1,420 msgs/sec. All ingress buffers normal.',
  },
  {
    name: 'PM Sync & CMMS Bridge',
    status: 'Degraded',
    lastUpdated: '2m ago',
    details: 'CMMS sync delay: 8 work orders queued in sync buffer. Automatic retry cycle in 3 minutes.',
    estimatedResolution: 'Resolving automatically within 10 minutes',
  },
  {
    name: 'Contract Ingestion Pipeline',
    status: 'Operational',
    lastUpdated: '5m ago',
    details: 'Document OCR and ERP contract sync fully reconciled. 5 contracts monitored.',
  },
  {
    name: 'AI Risk & Copilot Engine',
    status: 'Operational',
    lastUpdated: 'Just now',
    details: 'Inference latency 140ms. Continuous Bayesian fault scoring active across all 12 assets.',
  },
];
